// 100+ Product & Strategy Quotes for random display
export const QUOTES = [
    { text: "Building products that scale to", highlight: "millions" },
    { text: "Hope is not a", highlight: "strategy" },
    { text: "Move fast and break", highlight: "assumptions" },
    { text: "Measure what", highlight: "matters" },
    { text: "Simplicity is the ultimate", highlight: "sophistication" },
    { text: "Build for the user, not the", highlight: "stakeholder" },
    { text: "Data informs, intuition", highlight: "decides" },
    { text: "Ship it, then", highlight: "fix it" },
    { text: "Perfect is the enemy of", highlight: "done" },
    { text: "Constraints breed", highlight: "creativity" },
    { text: "Focus on outcomes, not", highlight: "outputs" },
    { text: "Fall in love with the problem, not the", highlight: "solution" },
    { text: "Done is better than", highlight: "perfect" },
    { text: "Think big, start", highlight: "small" },
    { text: "Your product is only as good as your", highlight: "team" },
    { text: "Culture eats strategy for", highlight: "breakfast" },
    { text: "The best code is no", highlight: "code" },
    { text: "Users don't know what they want until you", highlight: "show them" },
    { text: "Iterate or", highlight: "die" },
    { text: "Build the right thing, then build it", highlight: "right" },
    { text: "Feedback is a", highlight: "gift" },
    { text: "Complexity is the enemy of", highlight: "execution" },
    { text: "Launch and", highlight: "learn" },
    { text: "Good enough today beats perfect", highlight: "tomorrow" },
    { text: "Talk to users", highlight: "daily" },
    { text: "Prioritize ruthlessly, execute", highlight: "relentlessly" },
    { text: "Every feature has a", highlight: "cost" },
    { text: "Speed is a", highlight: "feature" },
    { text: "Consistency builds", highlight: "trust" },
    { text: "Defaults are", highlight: "decisions" },
    { text: "Design is how it", highlight: "works" },
    { text: "Details matter", highlight: "deeply" },
    { text: "Friction kills", highlight: "conversion" },
    { text: "Good design is", highlight: "invisible" },
    { text: "If you're not embarrassed by v1, you launched too", highlight: "late" },
    { text: "Innovation distinguishes leaders from", highlight: "followers" },
    { text: "Keep it simple,", highlight: "always" },
    { text: "Less is", highlight: "more" },
    { text: "Make it work, make it right, make it", highlight: "fast" },
    { text: "Prototype early, fail", highlight: "cheaply" },
    { text: "Quality is not an act, it's a", highlight: "habit" },
    { text: "Revenue is", highlight: "oxygen" },
    { text: "Roadmaps are", highlight: "intentions" },
    { text: "Say no to a thousand", highlight: "things" },
    { text: "Scaling is a marathon, not a", highlight: "sprint" },
    { text: "Show, don't", highlight: "tell" },
    { text: "Simple scales, complex", highlight: "fails" },
    { text: "Start with", highlight: "why" },
    { text: "Stay hungry, stay", highlight: "foolish" },
    { text: "Strategy is about making", highlight: "choices" },
    { text: "Strong opinions, loosely", highlight: "held" },
    { text: "The map is not the", highlight: "territory" },
    { text: "Think in systems, not", highlight: "screens" },
    { text: "Time to value is", highlight: "everything" },
    { text: "Trust the process, verify the", highlight: "results" },
    { text: "Understand the problem before", highlight: "solving it" },
    { text: "Velocity without direction is", highlight: "chaos" },
    { text: "Vision without execution is", highlight: "hallucination" },
    { text: "Work backwards from the", highlight: "customer" },
    { text: "Write the press release", highlight: "first" },
    { text: "Your MVP should make you", highlight: "cringe" },
    { text: "Zero to one beats one to", highlight: "many" },
    { text: "Assumptions are", highlight: "risks" },
    { text: "Automate the", highlight: "boring" },
    { text: "Be stubborn on vision, flexible on", highlight: "details" },
    { text: "Better inputs, better", highlight: "outputs" },
    { text: "Bias for", highlight: "action" },
    { text: "Build with empathy, ship with", highlight: "urgency" },
    { text: "Bureaucracy is the enemy of", highlight: "innovation" },
    { text: "Celebrate progress, not", highlight: "perfection" },
    { text: "Clarity is", highlight: "kindness" },
    { text: "Communication is the real", highlight: "work" },
    { text: "Compete on value, not", highlight: "features" },
    { text: "Context matters more than", highlight: "content" },
    { text: "Decisions should be reversible, not", highlight: "perfect" },
    { text: "Delight is in the", highlight: "details" },
    { text: "Disagree and", highlight: "commit" },
    { text: "Do things that don't", highlight: "scale" },
    { text: "Don't confuse motion with", highlight: "progress" },
    { text: "Don't optimize the wrong", highlight: "metric" },
    { text: "Every problem is a design", highlight: "opportunity" },
    { text: "Execution beats", highlight: "strategy" },
    { text: "Experience is the", highlight: "product" },
    { text: "Fail fast, learn", highlight: "faster" },
    { text: "Features are not", highlight: "solutions" },
    { text: "First principles beats", highlight: "analogy" },
    { text: "Focus beats", highlight: "frenzy" },
    { text: "Good judgment comes from", highlight: "experience" },
    { text: "Growth follows", highlight: "value" },
    { text: "Hire for potential, train for", highlight: "skills" },
    { text: "Hypotheses are not", highlight: "opinions" },
    { text: "Ideas are cheap, execution is", highlight: "expensive" },
    { text: "Impact over", highlight: "intent" },
    { text: "Insights beat", highlight: "data" },
    { text: "Intuition is compressed", highlight: "experience" },
    { text: "Invest in", highlight: "foundations" },
    { text: "It's not done until it's", highlight: "deployed" },
    { text: "Knowledge shared is knowledge", highlight: "multiplied" },
    { text: "Learn to love the", highlight: "plateau" },
    { text: "Listen more than you", highlight: "speak" },
    { text: "Loops beat", highlight: "lines" },
    { text: "Make the right thing the", highlight: "easy thing" },
    { text: "Mission over", highlight: "meetings" },
    { text: "Momentum is", highlight: "magic" },
    { text: "Never assume, always", highlight: "validate" },
    { text: "No plan survives contact with", highlight: "users" },
    { text: "Optimize for learning, not", highlight: "winning" },
    { text: "Ownership is", highlight: "accountability" },
    { text: "Pain points are product", highlight: "opportunities" },
    { text: "Patterns emerge from", highlight: "practice" },
    { text: "Progress is made by", highlight: "iterations" },
    { text: "Prototype to", highlight: "think" },
    { text: "Reduce, reuse,", highlight: "refactor" },
    { text: "Retention is the true north", highlight: "metric" },
    { text: "Risk is unavoidable, so", highlight: "manage it" },
    { text: "Scale what works, kill what", highlight: "doesn't" },
    { text: "Scope creep kills", highlight: "projects" },
    { text: "Shipping is a", highlight: "habit" },
    { text: "Slow is smooth, smooth is", highlight: "fast" },
    { text: "Small teams,", highlight: "big impact" },
    { text: "Solve for the 80%, not the", highlight: "edge case" },
    { text: "Stories beat", highlight: "specs" },
    { text: "Sustainability beats", highlight: "spikes" },
    { text: "Systems outlast", highlight: "individuals" },
    { text: "Tech debt is a", highlight: "choice" },
    { text: "The bottleneck is always", highlight: "upstream" },
    { text: "The goal isn't traffic, it's", highlight: "value" },
    { text: "Think in bets, not", highlight: "certainties" },
    { text: "Tools amplify", highlight: "talent" },
    { text: "Transparency builds", highlight: "trust" },
    { text: "Urgency is not", highlight: "rushing" },
    { text: "User research is not", highlight: "optional" },
    { text: "Validate before you", highlight: "build" },
    { text: "Vanity metrics", highlight: "lie" },
    { text: "Velocity is a means, not an", highlight: "end" },
    { text: "What gets measured gets", highlight: "managed" },
    { text: "When in doubt,", highlight: "ship it" },
    { text: "Win the morning, win the", highlight: "day" },
    { text: "Words matter, use them", highlight: "carefully" },
    { text: "Work on the business, not in", highlight: "it" },
    { text: "Write it down, make it", highlight: "real" },
    { text: "You are not your", highlight: "user" },
    { text: "Your backlog is a graveyard of", highlight: "ideas" },
];

export function getRandomQuote() {
    return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
